## Bernoulli-Naive-Bayes

In [17]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB 
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

In [26]:
X = np.array([[1, 0, 0],
              [1, 0, 1],
              [0, 1, 1],
              [0, 1, 0],
              [1, 1, 0],
              [0, 0, 1],
              #[0, 0, 0]
            ])
Y = np.array([0, 1, 0, 1, 1, 0])

X_test = np.array([[1, 1, 1]])

In [27]:
clf = BernoulliNB()

model = clf.fit(X, Y)

In [28]:
y_pred = clf.predict(X_test)
print(y_pred)

[1]


In [29]:
clf.predict_proba(X_test)

array([[0.4, 0.6]])

In [30]:
clf.predict_log_proba(X_test)

array([[-0.91629073, -0.51082562]])

In [31]:
np.exp(clf.class_log_prior_)

array([0.5, 0.5])

In [32]:
np.exp(clf.feature_log_prob_)

array([[0.4, 0.4, 0.6],
       [0.6, 0.6, 0.4]])