In [16]:
from sklearn.naive_bayes import CategoricalNB
import numpy as np

# Sunny -> 0
# Overcast -> 1
# Rainy -> 2

X_train = np.array([[0],
                  [1],
                  [2],
                  [0],
                  [0],
                  [1],
                  [2],
                  [2],
                  [0],
                  [2],
                  [0],              
                  [1],
                  [1],
                  [2]])
y_train = np.array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0])

In [17]:
# train a model

classifier = CategoricalNB()
clf = classifier.fit(X_train, y_train)

In [18]:
# predict for Sunny
X_test = np.array([[0]])
clf.predict_proba(X_test)

array([[0.38461538, 0.61538462]])

In [20]:
clf.category_count_

[array([[2., 0., 3.],
        [3., 4., 2.]])]

In [9]:
clf.class_count_

array([5., 9.])

In [12]:
np.exp(clf.class_log_prior_)

array([0.35714286, 0.64285714])

In [13]:
clf.classes_

array([0, 1])

In [14]:
np.exp(clf.feature_log_prob_)

array([[1.],
       [1.]])

## Compute manually

In [15]:
import math

def gaussian_function(data, mean, var):
    return (1.0/np.sqrt(2*math.pi*var)) * np.exp(-(data-mean)**2 / (2*var))

In [16]:
# compute manually

data_c0 = np.array([1.4, 1.0, 1.3, 1.9, 2.0])
mean_c0 = data_c0.mean()
var_c0  = data_c0.var()
print(mean_c0)
print(var_c0)      

prob_c0 = gaussian_function(data_c0, mean_c0, var_c0)
print(prob_c0)

1.52
0.1416
[1.00761742 0.40804972 0.893626   0.63670363 0.46995266]


In [17]:
data_c1 = np.array([3.8, 4.1, 3.9, 4.2, 3.4])
mean_c1 = data_c1.mean()
var_c1  = data_c1.var()
print(mean_c1)
print(var_c1)

prob_c1 = gaussian_function(data_c1, mean_c1, var_c1)
print(prob_c1)

3.88
0.07760000000000002
[1.37426395 1.0484362  1.42843305 0.74034542 0.3245289 ]


In [23]:
# predict manually

x_test = np.array([[3.0]])
dpf_c0_x = gaussian_function(x_test, mean_c0, var_c0)
dpf_c1_x = gaussian_function(x_test, mean_c1, var_c1)
print(dpf_c0_x)
print(dpf_c1_x)

# normalize
total = dpf_c0_x*0.5 + dpf_c1_x*0.5
print(total)
dpf_c0_x = dpf_c0_x*0.5/total
dpf_c1_x = dpf_c1_x*0.5/total

# print
print(dpf_c0_x)
print(dpf_c1_x)

[[0.00046381]]
[[0.00974954]]
[[0.00510668]]
[[0.0454125]]
[[0.9545875]]
